<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'jayden richards',
                'email' => 'jayden.richards@example.com',
                'avatar' => 'avatar-F97FC474-411A-2C20-0DED-F65F449A1D96.jpg',
                'slug' => 'jayden-richards',
                'password' => '$2y$10$CB2p/x/.tsUcQSB2VhojH.gLPrcnll6.7f1WGX8BWTlrtcKqVWIoi',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:29',
                'updated_at' => '2018-11-28 10:16:29',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'lærke pedersen',
                'email' => 'lærke.pedersen@example.com',
                'avatar' => 'avatar-8E1011C3-63F4-F7E2-D5F5-93467B5BF689.jpg',
                'slug' => 'laerke-pedersen',
                'password' => '$2y$10$zOQsPbvGmHUydoc4UAi8L.9Hp3pA7Ttkp1CGRcPdOF3beE4Avcn62',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:30',
                'updated_at' => '2018-11-28 10:16:30',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'micheal holland',
                'email' => 'micheal.holland@example.com',
                'avatar' => 'avatar-A897D92C-114C-BABD-3E6A-24B34DCB1E86.jpg',
                'slug' => 'micheal-holland',
                'password' => '$2y$10$ud9QoTRyAo.y7fDfDwvZje.CFPjIlOEQC9/i5PqsfA0TVi0pB61bm',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:31',
                'updated_at' => '2018-11-28 10:16:31',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'cléo durand',
                'email' => 'cléo.durand@example.com',
                'avatar' => 'avatar-65ECE1EE-D4AB-8669-317E-3DBCDEE6B972.jpg',
                'slug' => 'cleo-durand',
                'password' => '$2y$10$F1neGLNQHjdyxWdmFXkPeeolFjxyj8NtHgUZAi5KaJPzHqa9BwyY6',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:32',
                'updated_at' => '2018-11-28 10:16:32',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'lola king',
                'email' => 'lola.king@example.com',
                'avatar' => 'avatar-37F27809-5249-1BF9-70A4-EEA2CB8DC206.jpg',
                'slug' => 'lola-king',
                'password' => '$2y$10$AuV2Q/po15xxVvyzi1COSuQ53OQM.3YxYtcdgbshQBUHivyxrPBhu',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:33',
                'updated_at' => '2018-11-28 10:16:33',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'mille christensen',
                'email' => 'mille.christensen@example.com',
                'avatar' => 'avatar-CDA5FF35-85AD-31F1-F795-975B75060DB0.jpg',
                'slug' => 'mille-christensen',
                'password' => '$2y$10$3fi2Mn4UluCblVi9Hi7Bnes/IrMPhUi9Owa17OEW0/CG8tQdoVnQO',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:34',
                'updated_at' => '2018-11-28 10:16:34',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'teresa tucker',
                'email' => 'teresa.tucker@example.com',
                'avatar' => 'avatar-531AF45A-B08B-E1DB-4CB5-0B85A1B0DC03.jpg',
                'slug' => 'teresa-tucker',
                'password' => '$2y$10$IlPAF/k1NHW6EpAUjUmvI.zu3PiRLhq9B1DmvYZeQklPK158ZVn8y',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:35',
                'updated_at' => '2018-11-28 10:16:35',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'mélina petit',
                'email' => 'mélina.petit@example.com',
                'avatar' => 'avatar-C77DA2A8-430C-31DF-D0F3-DF5B1F62C6B6.jpg',
                'slug' => 'melina-petit',
                'password' => '$2y$10$IXiR2d3B/6rLBLsGMpcUi.tiY0ie2cuuZCNGzm8bMbTWt9lx2urPi',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:36',
                'updated_at' => '2018-11-28 10:16:36',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'tracy byrd',
                'email' => 'tracy.byrd@example.com',
                'avatar' => 'avatar-40A73E00-0056-80BD-6C0E-83CD3392E1A3.jpg',
                'slug' => 'tracy-byrd',
                'password' => '$2y$10$vEfDWKe4c8QTtFNUFk/xDO43lNCSLdVzR9ag/Etd.US1V7S/GrXXS',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:37',
                'updated_at' => '2018-11-28 10:16:37',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'nicoline mortensen',
                'email' => 'nicoline.mortensen@example.com',
                'avatar' => 'avatar-90796F7B-A199-8D9B-309B-A011732DE3F2.jpg',
                'slug' => 'nicoline-mortensen',
                'password' => '$2y$10$Jjy2qx7Dzz1DENtVQvgnXeo.TsErAMMu34jKhbzYHz5F7.Q/qbCEC',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:38',
                'updated_at' => '2018-11-28 10:16:38',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'anton rasmussen',
                'email' => 'anton.rasmussen@example.com',
                'avatar' => 'avatar-223B7CE1-29D0-F7C3-48A3-9B4C729DC931.jpg',
                'slug' => 'anton-rasmussen',
                'password' => '$2y$10$bkS/DS.Qsa6qHPqMxXwBoOHQwLsUaUVHQED.JcMOoNaowvgbncqm6',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:39',
                'updated_at' => '2018-11-28 10:16:39',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'maëlia francois',
                'email' => 'maëlia.francois@example.com',
                'avatar' => 'avatar-73DE9D22-F5CD-D212-C377-686CEF1D2A6A.jpg',
                'slug' => 'maelia-francois',
                'password' => '$2y$10$X4siwP5pumCF1UdjxJbeleXdyqcS6cJvhMUQXHG2bTIm3/EKI4S8O',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:40',
                'updated_at' => '2018-11-28 10:16:40',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'eloïse morin',
                'email' => 'eloïse.morin@example.com',
                'avatar' => 'avatar-9F4D3ADF-53AB-19CD-E9E0-D3B60AD4E7A9.jpg',
                'slug' => 'eloise-morin',
                'password' => '$2y$10$8ry3BiyGbr1ZZb7HbhwvUelZ2lbAqVinifdJ4rnNMPF2aYFyEpsOa',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:41',
                'updated_at' => '2018-11-28 10:16:41',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'clara møller',
                'email' => 'clara.møller@example.com',
                'avatar' => 'avatar-B6F66CB7-0136-508E-72C3-D9A28319A2D4.jpg',
                'slug' => 'clara-moller',
                'password' => '$2y$10$OATs23KOrNcFYD40B5n5iuwg2Jy1m.kIcegSwpJ9IltT.hlBEy/QK',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:42',
                'updated_at' => '2018-11-28 10:16:42',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'emeline meunier',
                'email' => 'emeline.meunier@example.com',
                'avatar' => 'avatar-3E696482-7857-3038-B2D1-D2D48B6340D3.jpg',
                'slug' => 'emeline-meunier',
                'password' => '$2y$10$qN6SuTUdxG8hTS4SMZPfEun/36FUnx469rhZajndMG97mERDc1SXy',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:43',
                'updated_at' => '2018-11-28 10:16:43',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'ted hudson',
                'email' => 'ted.hudson@example.com',
                'avatar' => 'avatar-173FD33C-C7E9-6ED5-DD69-005AF4CB3F07.jpg',
                'slug' => 'ted-hudson',
                'password' => '$2y$10$3t14Us1i/SfrosIKANF4TOe0kl1JADSKryZmf4feuixXQXdQyqLKG',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:45',
                'updated_at' => '2018-11-28 10:16:45',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'daniel johansen',
                'email' => 'daniel.johansen@example.com',
                'avatar' => 'avatar-C6D7E56B-A16A-09AC-8D49-BB682AA162DE.jpg',
                'slug' => 'daniel-johansen',
                'password' => '$2y$10$u2jT7nFUN7YB6/CzhnPmpONC.NsII.K1V35SY4894gzU3AF2F0rey',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:46',
                'updated_at' => '2018-11-28 10:16:46',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'mary kennedy',
                'email' => 'mary.kennedy@example.com',
                'avatar' => 'avatar-A5D257F7-D9E2-5209-69CA-9B5885942BD4.jpg',
                'slug' => 'mary-kennedy',
                'password' => '$2y$10$aJaa4eJiA7GvSCmalFNFEea6ziYoDyf2ceDbE/H.HVZFBi4LJluqq',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:47',
                'updated_at' => '2018-11-28 10:16:47',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'stanley jenkins',
                'email' => 'stanley.jenkins@example.com',
                'avatar' => 'avatar-70984DB5-8FBF-6C50-F9CA-60583D0B63F1.jpg',
                'slug' => 'stanley-jenkins',
                'password' => '$2y$10$eldZ6Pg4JfCZ5CwmYGJI0OUAOhJYWqP9uLb.h/BQrlmPStRJwx7bO',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:48',
                'updated_at' => '2018-11-28 10:16:48',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'carl christensen',
                'email' => 'carl.christensen@example.com',
                'avatar' => 'avatar-6F1E198F-55AB-2773-99EC-787FA0F4B522.jpg',
                'slug' => 'carl-christensen',
                'password' => '$2y$10$mJ.x1yQN0pe4K/yW3NfG6OrXWLFrtXOoeZA3RlQUQQRnI0tRGgXhm',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:49',
                'updated_at' => '2018-11-28 10:16:49',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'adèle arnaud',
                'email' => 'adèle.arnaud@example.com',
                'avatar' => 'avatar-203C5E90-161A-5F0E-472E-947925B73240.jpg',
                'slug' => 'adele-arnaud',
                'password' => '$2y$10$tXbBmrSQkuXOvaXcAQCFIOozURG1h6gF8SMaEqI6FfRUmFpCXcQqe',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:50',
                'updated_at' => '2018-11-28 10:16:50',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'emma rousseau',
                'email' => 'emma.rousseau@example.com',
                'avatar' => 'avatar-FB507D35-6609-D11E-450F-050CA6ADEAE7.jpg',
                'slug' => 'emma-rousseau',
                'password' => '$2y$10$j5S6mQwK7ECBgt1eM5KWnu7D8TzFWJ0T3HZZUDZrlTlyDHu.HilFW',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:51',
                'updated_at' => '2018-11-28 10:16:51',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'villads christensen',
                'email' => 'villads.christensen@example.com',
                'avatar' => 'avatar-6034AA3E-6888-D169-26CE-CE945EFD6D91.jpg',
                'slug' => 'villads-christensen',
                'password' => '$2y$10$QC30VROaYTVbK6VDfcaN1ulKWR37JlbWk4UiV4os.Qvwj6AeIjK9e',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:52',
                'updated_at' => '2018-11-28 10:16:52',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'jacob thomsen',
                'email' => 'jacob.thomsen@example.com',
                'avatar' => 'avatar-53D441CB-7C83-5826-676D-B84BBA288E09.jpg',
                'slug' => 'jacob-thomsen',
                'password' => '$2y$10$tzBROXYRNbyYBXlbR6WZW.ljCFvf9qOYve1PwbNNV0Pf7p6xVM0gO',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:53',
                'updated_at' => '2018-11-28 10:16:53',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'emmy mathieu',
                'email' => 'emmy.mathieu@example.com',
                'avatar' => 'avatar-01F6E27A-FA7C-1C4C-5933-5E16A1D8B9FF.jpg',
                'slug' => 'emmy-mathieu',
                'password' => '$2y$10$HDOE5dFvk.eeHuxf/4GStun.SvhBOresIffTC12OmQh4zAjD/nYti',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:54',
                'updated_at' => '2018-11-28 10:16:54',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'warren hudson',
                'email' => 'warren.hudson@example.com',
                'avatar' => 'avatar-BA813DE3-93C6-92C9-E301-C429AE91C61F.jpg',
                'slug' => 'warren-hudson',
                'password' => '$2y$10$tVCZpE7ekTG5OZwm3jPf2e.Svx/2tIjs5Ayflg0.tzJR2w0wGLpOK',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:55',
                'updated_at' => '2018-11-28 10:16:55',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'selma sørensen',
                'email' => 'selma.sørensen@example.com',
                'avatar' => 'avatar-94438EDF-39B4-1DFD-BA59-82E485A8C221.jpg',
                'slug' => 'selma-sorensen',
                'password' => '$2y$10$QQWOQviPZ./FbIMFeKuTyuG6Lg3yMb9/Xz9Mk4lWPP7EzeO4G9xNm',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:56',
                'updated_at' => '2018-11-28 10:16:56',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'anton andersen',
                'email' => 'anton.andersen@example.com',
                'avatar' => 'avatar-FE7F996B-9C25-C18A-09EA-211F79EBB0A8.jpg',
                'slug' => 'anton-andersen',
                'password' => '$2y$10$eQZrUt3CcYy61V9kGdQGaOJKCMFaR/ZikWR9Y1O.iHbayUq1DAUZ6',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:57',
                'updated_at' => '2018-11-28 10:16:57',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'taylor riley',
                'email' => 'taylor.riley@example.com',
                'avatar' => 'avatar-408AB8F9-489E-6445-694A-BACB8C2791E5.jpg',
                'slug' => 'taylor-riley',
                'password' => '$2y$10$CUxW7NFmenAmnVUGpESRIeSkTUG8iUWw7shQcrIrlmk4a3/F8HWDW',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:58',
                'updated_at' => '2018-11-28 10:16:58',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'guillaume michel',
                'email' => 'guillaume.michel@example.com',
                'avatar' => 'avatar-77C39BAB-12FD-FA52-51DD-5A4A8A20BD14.jpg',
                'slug' => 'guillaume-michel',
                'password' => '$2y$10$MkCkMyuZzcq3oIQkhkZVCexF/er9b/ISYda8lgB6v0jNiPjgc25Mm',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:16:59',
                'updated_at' => '2018-11-28 10:16:59',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'johanne rasmussen',
                'email' => 'johanne.rasmussen@example.com',
                'avatar' => 'avatar-53206D10-5729-8340-1425-E209341CD772.jpg',
                'slug' => 'johanne-rasmussen',
                'password' => '$2y$10$qmsa8iQo87IAu/VkVWFymunRyNPZqrqaYaGaO4wO/0arKugwtmDe.',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:17:00',
                'updated_at' => '2018-11-28 10:17:00',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'emilie rasmussen',
                'email' => 'emilie.rasmussen@example.com',
                'avatar' => 'avatar-13D42DAB-6F98-5D5F-BF33-28A16D31C5CF.jpg',
                'slug' => 'emilie-rasmussen',
                'password' => '$2y$10$BsSMyg4ZUcmcxxhkY2T19eEx6dzhyxo3kPX5f3LmGaRsX.lyF8ETe',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:17:01',
                'updated_at' => '2018-11-28 10:17:01',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'jacob olsen',
                'email' => 'jacob.olsen@example.com',
                'avatar' => 'avatar-6CE866DD-5D95-076F-888C-CA15AF95A400.jpg',
                'slug' => 'jacob-olsen',
                'password' => '$2y$10$V3kp6grezTSGVwpuKNDpTuKsQmMpyOxicYfmoB7mBDOi9jRvIXLmK',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:17:02',
                'updated_at' => '2018-11-28 10:17:02',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'katherine tucker',
                'email' => 'katherine.tucker@example.com',
                'avatar' => 'avatar-CDDD9D87-78F1-F34D-EE0B-3227EBCCDAC7.jpg',
                'slug' => 'katherine-tucker',
                'password' => '$2y$10$IvG6udevw/Z9osdsJere8e3Kt5TqtR0jgmPiM21.oXuQCJxZqmbge',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:17:03',
                'updated_at' => '2018-11-28 10:17:03',
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'jessica davies',
                'email' => 'jessica.davies@example.com',
                'avatar' => 'avatar-C12D72B5-C1CD-68A1-7797-D48AE14FA4D4.jpg',
                'slug' => 'jessica-davies',
                'password' => '$2y$10$2cGmVkJhKNJ632KqMSWQpu1b0LV4q2Wh0kOo9TMtV8n2VBf4pAvL.',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:17:04',
                'updated_at' => '2018-11-28 10:17:04',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'matthew richards',
                'email' => 'matthew.richards@example.com',
                'avatar' => 'avatar-6CB8D20B-BB6C-06C1-46C5-D41EC1C1980F.jpg',
                'slug' => 'matthew-richards',
                'password' => '$2y$10$C76kFK7GO2ppTJOPetDvF.asj/dKU2E4DFb0mY3ArNa53iTRylMcO',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:17:05',
                'updated_at' => '2018-11-28 10:17:05',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'nelson ruiz',
                'email' => 'nelson.ruiz@example.com',
                'avatar' => 'avatar-195332E8-7ADA-0CFE-D7DD-3726CB0911EF.jpg',
                'slug' => 'nelson-ruiz',
                'password' => '$2y$10$76AfxO7IelFID4uy6RHN6OR/3iXvW.jrgQa7B56BrO7uxHWzZYhjO',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:17:06',
                'updated_at' => '2018-11-28 10:17:06',
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'tonya sanchez',
                'email' => 'tonya.sanchez@example.com',
                'avatar' => 'avatar-B7E71FD7-A9B7-91F8-90A6-BAA9D067B406.jpg',
                'slug' => 'tonya-sanchez',
                'password' => '$2y$10$GF89h9bcenyQRacoTFbRlOYKrED3T7.xRbH6/ptRP4Ivzxqfuxcka',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:17:07',
                'updated_at' => '2018-11-28 10:17:07',
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'floyd kuhn',
                'email' => 'floyd.kuhn@example.com',
                'avatar' => 'avatar-F133425A-7C91-3CA0-9BC5-37C706DD0EC8.jpg',
                'slug' => 'floyd-kuhn',
                'password' => '$2y$10$Eey5Ip1995RXBWJjbzfpo.njlrQEyLsbCA0Ut32nFH168BbfBGWRe',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:17:08',
                'updated_at' => '2018-11-28 10:17:08',
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'lucien jean',
                'email' => 'lucien.jean@example.com',
                'avatar' => 'avatar-229E0DEC-3ABA-BA46-32D5-74C587FB470A.jpg',
                'slug' => 'lucien-jean',
                'password' => '$2y$10$MvKPWqTxYjDJ.voasqJHDODnOkN6EIVnfhWN7nH0jeGCJZMWLhx56',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:17:10',
                'updated_at' => '2018-11-28 10:17:10',
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'leon armstrong',
                'email' => 'leon.armstrong@example.com',
                'avatar' => 'avatar-55B775FC-F799-787B-C506-43C0A4589606.jpg',
                'slug' => 'leon-armstrong',
                'password' => '$2y$10$F4XxyyFf4lmBREL1bB68Q.fX4Ghmp2T1yJQeE883ajy9dhRiSCZWy',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:17:11',
                'updated_at' => '2018-11-28 10:17:11',
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'axelle lefevre',
                'email' => 'axelle.lefevre@example.com',
                'avatar' => 'avatar-4D245C34-F502-2AAF-0689-5213407A45B4.jpg',
                'slug' => 'axelle-lefevre',
                'password' => '$2y$10$Ta2HvzmZBHShsIK.v2z3FuIVrJY1tsqjSOCOY7v7qJNPZ89cJPU5e',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:17:12',
                'updated_at' => '2018-11-28 10:17:12',
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'florence coleman',
                'email' => 'florence.coleman@example.com',
                'avatar' => 'avatar-E3EF5011-F318-DC9A-AF93-DC78F752C993.jpg',
                'slug' => 'florence-coleman',
                'password' => '$2y$10$muUJlZkgDJcBKMspqhqdHOzj3WQlh4FMWJ3nTmCZ.1hcp5u/6NMzW',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:17:13',
                'updated_at' => '2018-11-28 10:17:13',
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'angel gutierrez',
                'email' => 'angel.gutierrez@example.com',
                'avatar' => 'avatar-93F40863-CFAA-134F-D8FA-397012D3871D.jpg',
                'slug' => 'angel-gutierrez',
                'password' => '$2y$10$z3b8QuKxMPQaQSNa/GFExuWGDEHse/f/hmLzBmdRw2WPfpAZXXle2',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:17:14',
                'updated_at' => '2018-11-28 10:17:14',
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'cecilie sørensen',
                'email' => 'cecilie.sørensen@example.com',
                'avatar' => 'avatar-D29AD194-7771-064C-9897-313B39370105.jpg',
                'slug' => 'cecilie-sorensen',
                'password' => '$2y$10$voYHz2eH3bYDxyIUBEWxIuS1Tiv4WMkIa1kacFdcd4hVN/rwShrky',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:17:15',
                'updated_at' => '2018-11-28 10:17:15',
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'hunter myers',
                'email' => 'hunter.myers@example.com',
                'avatar' => 'avatar-D15F8102-311E-5F7A-7D95-94188FD528A0.jpg',
                'slug' => 'hunter-myers',
                'password' => '$2y$10$wIMNVoHq5yDLBHbGoUCKxOQE4YGWaXc4nkTI3rfGSpFzzLrL8GHXy',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:17:16',
                'updated_at' => '2018-11-28 10:17:16',
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'marin blanchard',
                'email' => 'marin.blanchard@example.com',
                'avatar' => 'avatar-575520CA-CD2F-A5F7-7AB5-45D56CB75527.jpg',
                'slug' => 'marin-blanchard',
                'password' => '$2y$10$aFLjjMNXnLCe0Snv0kMeO.SwlLMdU1uHOzFecwo6Yp6ReVy2ZgTVC',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:17:17',
                'updated_at' => '2018-11-28 10:17:17',
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'brian wright',
                'email' => 'brian.wright@example.com',
                'avatar' => 'avatar-6D52483C-6E72-FE80-E03A-CBE385BFC2F2.jpg',
                'slug' => 'brian-wright',
                'password' => '$2y$10$jWOTXvQ60BihedQWgxr0vuhgkBPkI5n4iaoQfWs0v8bRupyHWTwEa',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:17:18',
                'updated_at' => '2018-11-28 10:17:18',
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'roland hicks',
                'email' => 'roland.hicks@example.com',
                'avatar' => 'avatar-23E2BB60-46E4-8286-E686-7177DA6DBACE.jpg',
                'slug' => 'roland-hicks',
                'password' => '$2y$10$I0h2xxf2E9Pw7ol5VND7euIUsBVmGW6arBdvL0klvJIlgk9M3Fc0G',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:17:19',
                'updated_at' => '2018-11-28 10:17:19',
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'riley mitchell',
                'email' => 'riley.mitchell@example.com',
                'avatar' => 'avatar-66BE0AFD-AE0D-20D6-6405-A8562721C844.jpg',
                'slug' => 'riley-mitchell',
                'password' => '$2y$10$6rZioPAA2RP4CuX6algZx.W8naJuEAunQCE.kSvGHvW.gIKiHuDGK',
                'bio' => NULL,
                'facebook_id' => NULL,
                'google_id' => NULL,
                'is_active' => 0,
                'remember_token' => NULL,
                'created_at' => '2018-11-28 10:17:20',
                'updated_at' => '2018-11-28 10:17:20',
            ),
        ));
        
        
    }
}