    <article class="post bb-post post-stream bb-card-item post-412 type-post status-publish format-standard has-post-thumbnail category-sport category-video tag-sport tag-video">
                                        <h2 class="entry-title"><a href="https://boombox.px-lab.com/another-gag/cool/" rel="bookmark"  >Cool</a></h2>
                                        <div class="post-thumbnail">
                                            <div class="video-wrapper boombox-featured-video " style="background-image:url(https://boombox.px-lab.com/another-gag/wp-content/uploads/sites/3/2017/09/59cd5d3c8dd62_610942375.jpg)">
                                                <video width="100%" height="auto" loop>
                                                    <source src="https://boombox.px-lab.com/another-gag/wp-content/uploads/sites/3/2017/09/610942375.mp4" type="video/mp4"><img src="https://boombox.px-lab.com/another-gag/wp-content/uploads/sites/3/2017/09/59cd5d3c8dd62_610942375.jpg?x46754" title="To view this video please enable JavaScript, and consider upgrading to a web browser that supports HTML5 video"> </video> <span class="bb-btn-circle btn-lg btn-play"><i class="bb-icon bb-ui-icon-video"></i></span> <span class="bb-btn-circle btn-sm btn-volume"> <i class="volume-off bb-icon bb-ui-icon-volume-mute hidden"></i> <i class="volume-on bb-icon bb-ui-icon-volume-up "></i> </span> <span class="badge-duration hidden"></span></div>
                                            <a class="view-full-post" href="https://boombox.px-lab.com/another-gag/cool/"> <span class="bb-btn bb-btn-primary">View Full Post</span> </a>
                                        </div>
                                        <div class="content">
                                            <header class="entry-header"> </header>
                                        </div>
                                        <footer class="entry-footer">
                                            <div class="bb-post-share-box">
                                                <div class="content has-share-buttons">
                                                    <div class="bb-post-rating post-rating js-post-point" data-post_id="412">
                                                        <div class="inner">
                                                            <button class="up point-btn" data-action="up"> <i class="bb-icon bb-ui-icon-arrow-up"></i> </button>
                                                            <button class="down point-btn" data-action="down"> <i class="bb-icon bb-ui-icon-arrow-down"></i> </button> <span class="count"> <i class="bb-icon spinner-pulse"></i> <span class="text" label="points">938</span> </span>
                                                        </div>
                                                    </div>
                                                    <div class="post-meta bb-post-meta size-lg"><a href="https://boombox.px-lab.com/another-gag/cool/#comments" class="post-meta-item post-comments"><i class="bb-icon bb-ui-icon-comment"></i><span class="count">6</span></a></div>
                                                    <div class="essb_links essb_counters essb_displayed_boombox essb_share essb_template_default4-retina essb_template_glow-retina essb_470840280 essb_width_flex essb_links_center print-no" id="essb_displayed_boombox_470840280" data-essb-postid="412" data-essb-position="boombox" data-essb-button-style="button" data-essb-template="default4-retina essb_template_glow-retina" data-essb-counter-pos="hidden" data-essb-url="https://boombox.px-lab.com/another-gag/cool/" data-essb-twitter-url="https://boombox.px-lab.com/another-gag/cool/" data-essb-instance="470840280">
                                                        <ul class="essb_links_list">
                                                            <li class="essb_item essb_totalcount_item" style="display: none !important;" data-counter-pos="hidden"><span class="essb_totalcount essb_t_l" title="Total: "><span class="essb_total_text">Total: </span><span class="essb_t_nb">8</span></span>
                                                            </li>
                                                            <li class="essb_item essb_link_facebook nolightbox"> <a href="https://www.facebook.com/sharer/sharer.php?u=https://boombox.px-lab.com/another-gag/cool/&t=Cool" title="" onclick="essb.window(&#39;https://www.facebook.com/sharer/sharer.php?u=https://boombox.px-lab.com/another-gag/cool/&t=Cool&#39;,&#39;facebook&#39;,&#39;470840280&#39;); return false;" target="_blank" rel="nofollow"><span class="essb_icon essb_icon_facebook"></span><span class="essb_network_name">Facebook</span></a><span class="essb_counter_hidden" data-cnt="4" data-cnt-short=""></span></li>
                                                            <li class="essb_item essb_link_pinterest nolightbox"> <a href="#" title="" onclick="essb.pinterest_picker(&#39;470840280&#39;); return false;" target="_blank" rel="nofollow"><span class="essb_icon essb_icon_pinterest"></span><span class="essb_network_name">Pinterest</span></a><span class="essb_counter_hidden" data-cnt="" data-cnt-short=""></span></li>
                                                            <li class="essb_item essb_link_more_dots nolightbox"> <a href="#" title="" onclick="essb.toggle_more_popup(&#39;470840280&#39;); return false;" target="_blank" rel="nofollow"><span class="essb_icon essb_icon_more_dots"></span><span class="essb_network_name essb_noname"></span></a></li>
                                                            <li class="essb_item essb_link_twitter nolightbox essb_after_more"> <a href="#" title="" onclick="essb.window(&#39;https://twitter.com/intent/tweet?text=Cool&amp;url=https://boombox.px-lab.com/another-gag/cool/&amp;counturl=https://boombox.px-lab.com/another-gag/cool/&#39;,&#39;twitter&#39;,&#39;470840280&#39;); return false;" target="_blank" rel="nofollow"><span class="essb_icon essb_icon_twitter"></span><span class="essb_network_name">Twitter</span></a><span class="essb_counter_hidden" data-cnt="4" data-cnt-short=""></span></li>
                                                            <li class="essb_item essb_link_reddit nolightbox essb_after_more"> <a href="http://reddit.com/submit?url=https://boombox.px-lab.com/another-gag/cool/&amp;title=Cool" title="" onclick="essb.window(&#39;http://reddit.com/submit?url=https://boombox.px-lab.com/another-gag/cool/&amp;title=Cool&#39;,&#39;reddit&#39;,&#39;470840280&#39;); return false;" target="_blank" rel="nofollow"><span class="essb_icon essb_icon_reddit"></span><span class="essb_network_name">Reddit</span></a><span class="essb_counter_hidden" data-cnt="" data-cnt-short=""></span></li>
                                                            <li class="essb_item essb_link_tumblr nolightbox essb_after_more"> <a href="http://tumblr.com/share?s=&v=3&t=Cool&u=https%3A%2F%2Fboombox.px-lab.com%2Fanother-gag%2Fcool%2F" title="" onclick="essb.window(&#39;http://tumblr.com/share?s=&v=3&t=Cool&u=https%3A%2F%2Fboombox.px-lab.com%2Fanother-gag%2Fcool%2F&#39;,&#39;tumblr&#39;,&#39;470840280&#39;); return false;" target="_blank" rel="nofollow"><span class="essb_icon essb_icon_tumblr"></span><span class="essb_network_name">Tumblr</span></a></li>
                                                            <li class="essb_item essb_link_google nolightbox essb_after_more"> <a href="https://plus.google.com/share?url=https://boombox.px-lab.com/another-gag/cool/" title="" onclick="essb.window(&#39;https://plus.google.com/share?url=https://boombox.px-lab.com/another-gag/cool/&#39;,&#39;google&#39;,&#39;470840280&#39;); return false;" target="_blank" rel="nofollow"><span class="essb_icon essb_icon_google"></span><span class="essb_network_name">Google+</span></a><span class="essb_counter_hidden" data-cnt="" data-cnt-short=""></span></li>
                                                            <li class="essb_item essb_link_blogger nolightbox essb_after_more"> <a href="https://www.blogger.com/blog_this.pyra?t&u=https://boombox.px-lab.com/another-gag/cool/&n=Cool" title="" onclick="essb.window(&#39;https://www.blogger.com/blog_this.pyra?t&u=https://boombox.px-lab.com/another-gag/cool/&n=Cool&#39;,&#39;blogger&#39;,&#39;470840280&#39;); return false;" target="_blank" rel="nofollow"><span class="essb_icon essb_icon_blogger"></span><span class="essb_network_name">Blogger</span></a></li>
                                                        </ul>
                                                    </div>
                                                    <div class="essb_morepopup essb_morepopup_470840280 essb_morepopup_boombox essb_morepopup_inline" style="display:none;"> <a href="#" class="essb_morepopup_close" onclick="essb.toggle_less_popup('470840280'); return false;"><i class="essb_icon_close"></i></a>
                                                        <div class="essb_morepopup_content essb_morepopup_content_470840280">
                                                            <div class="essb_links essb_displayed_more_popup essb_share essb_template_default4-retina essb_template_glow-retina essb_1575378768 essb_links_center print-no" id="essb_displayed_more_popup_1575378768" data-essb-postid="412" data-essb-position="more_popup" data-essb-button-style="icon" data-essb-template="default4-retina essb_template_glow-retina" data-essb-counter-pos="left" data-essb-url="https://boombox.px-lab.com/another-gag/cool/" data-essb-twitter-url="https://boombox.px-lab.com/another-gag/cool/" data-essb-instance="1575378768">
                                                                <ul class="essb_links_list essb_force_hide_name essb_force_hide">
                                                                    <li class="essb_item essb_link_twitter nolightbox"> <a href="#" title="" onclick="essb.window(&#39;https://twitter.com/intent/tweet?text=Cool&amp;url=https://boombox.px-lab.com/another-gag/cool/&amp;counturl=https://boombox.px-lab.com/another-gag/cool/&#39;,&#39;twitter&#39;,&#39;1575378768&#39;); return false;" target="_blank" rel="nofollow"><span class="essb_icon essb_icon_twitter"></span><span class="essb_network_name essb_noname"></span></a></li>
                                                                    <li class="essb_item essb_link_reddit nolightbox"> <a href="http://reddit.com/submit?url=https://boombox.px-lab.com/another-gag/cool/&amp;title=Cool" title="" onclick="essb.window(&#39;http://reddit.com/submit?url=https://boombox.px-lab.com/another-gag/cool/&amp;title=Cool&#39;,&#39;reddit&#39;,&#39;1575378768&#39;); return false;" target="_blank" rel="nofollow"><span class="essb_icon essb_icon_reddit"></span><span class="essb_network_name essb_noname"></span></a></li>
                                                                    <li class="essb_item essb_link_tumblr nolightbox"> <a href="http://tumblr.com/share?s=&v=3&t=Cool&u=https%3A%2F%2Fboombox.px-lab.com%2Fanother-gag%2Fcool%2F" title="" onclick="essb.window(&#39;http://tumblr.com/share?s=&v=3&t=Cool&u=https%3A%2F%2Fboombox.px-lab.com%2Fanother-gag%2Fcool%2F&#39;,&#39;tumblr&#39;,&#39;1575378768&#39;); return false;" target="_blank" rel="nofollow"><span class="essb_icon essb_icon_tumblr"></span><span class="essb_network_name essb_noname"></span></a></li>
                                                                    <li class="essb_item essb_link_google nolightbox"> <a href="https://plus.google.com/share?url=https://boombox.px-lab.com/another-gag/cool/" title="" onclick="essb.window(&#39;https://plus.google.com/share?url=https://boombox.px-lab.com/another-gag/cool/&#39;,&#39;google&#39;,&#39;1575378768&#39;); return false;" target="_blank" rel="nofollow"><span class="essb_icon essb_icon_google"></span><span class="essb_network_name essb_noname"></span></a></li>
                                                                    <li class="essb_item essb_link_blogger nolightbox"> <a href="https://www.blogger.com/blog_this.pyra?t&u=https://boombox.px-lab.com/another-gag/cool/&n=Cool" title="" onclick="essb.window(&##39;https://www.blogger.com/blog_this.pyra?t&u=https://boombox.px-lab.com/another-gag/cool/&n=Cool&#39;,&#39;blogger&#39;,&#39;1575378768&#39;); return false;" target="_blank" rel="nofollow"><span class="essb_icon essb_icon_blogger"></span><span class="essb_network_name essb_noname"></span></a></li>
                                                                </ul>
                                                            </div>
                                                        </div>
                                                        <div class="modal-pointer modal-pointer-up-left">
                                                            <div class="modal-pointer-conceal"></div>
                                                        </div>
                                                    </div>
                                                    <div class="essb_morepopup_shadow essb_morepopup_shadow_470840280" onclick="essb.toggle_less_popup('470840280'); return false;"></div>
                                                    <div class="mobile-info"><span class="mobile-comments-count">6</span> comments, <span class="mobile-shares-count">8</span> shares, <span class="mobile-votes-count">938</span> points</div>
                                                </div>
                                            </div>
                                        </footer>
                                    </article>